"""Stubs for ``odoo.tests.common``.

Covers the unittest-style assert surface and ``env`` accessor that
addon tests use. Mirrors the same Any-returning design as
``odoo.models`` — pyright catches missing methods (typo in
``self.aassertEqual``) but not value-level mismatches inside the
unittest assertions (which is fine; those are runtime checks).
"""

from typing import Any

from odoo.models import Environment


class BaseCase:
    env: Environment

    @classmethod
    def setUpClass(cls) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...

    # unittest-style assertions; argument types loose because the addon
    # passes a mix of records, ints, strings, and Any-typed values.
    def assertEqual(self, first: Any, second: Any, msg: str | None = ...) -> None: ...
    def assertNotEqual(self, first: Any, second: Any, msg: str | None = ...) -> None: ...
    def assertTrue(self, expr: Any, msg: str | None = ...) -> None: ...
    def assertFalse(self, expr: Any, msg: str | None = ...) -> None: ...
    def assertIs(self, first: Any, second: Any, msg: str | None = ...) -> None: ...
    def assertIsNot(self, first: Any, second: Any, msg: str | None = ...) -> None: ...
    def assertIsNone(self, obj: Any, msg: str | None = ...) -> None: ...
    def assertIsNotNone(self, obj: Any, msg: str | None = ...) -> None: ...
    def assertIn(self, member: Any, container: Any, msg: str | None = ...) -> None: ...
    def assertNotIn(self, member: Any, container: Any, msg: str | None = ...) -> None: ...
    def assertGreater(self, first: Any, second: Any, msg: str | None = ...) -> None: ...
    def assertLess(self, first: Any, second: Any, msg: str | None = ...) -> None: ...
    def assertRaises(self, exc: type[BaseException]) -> Any: ...


class TransactionCase(BaseCase): ...
class SingleTransactionCase(BaseCase): ...
class HttpCase(BaseCase): ...
