"""Stubs for ``odoo.api``.

Covers the decorator surface parqcast actually imports. ``model`` is the
only one used today; the others are forward-compatibility for likely
future addon work (reactive depends, constraints, onchanges).
"""

from collections.abc import Callable
from typing import Any

def model[F: Callable[..., Any]](func: F) -> F: ...
def depends[F: Callable[..., Any]](*fields: str) -> Callable[[F], F]: ...
def depends_context[F: Callable[..., Any]](*keys: str) -> Callable[[F], F]: ...
def constrains[F: Callable[..., Any]](*fields: str) -> Callable[[F], F]: ...
def onchange[F: Callable[..., Any]](*fields: str) -> Callable[[F], F]: ...
def model_create_multi[F: Callable[..., Any]](func: F) -> F: ...
