"""Stubs for ``odoo.api``.

Covers the decorator surface parqcast actually imports. ``model`` is the
only one used today; the others are forward-compatibility for likely
future addon work (reactive depends, constraints, onchanges).
"""

from collections.abc import Callable
from typing import Any, TypeVar

F = TypeVar("F", bound=Callable[..., Any])

def model(func: F) -> F: ...
def depends(*fields: str) -> Callable[[F], F]: ...
def depends_context(*keys: str) -> Callable[[F], F]: ...
def constrains(*fields: str) -> Callable[[F], F]: ...
def onchange(*fields: str) -> Callable[[F], F]: ...
def model_create_multi(func: F) -> F: ...
