"""Stubs for ``odoo.fields``.

Each ``Field`` subclass accepts ``*args, **kwargs`` because Odoo's real
field constructors take dozens of keyword arguments (string, default,
help, required, readonly, related, compute, store, index, translate,
groups, copy, tracking, …) that are stable across versions but tedious
to enumerate. The trade-off is documented at module level — pyright
catches missing imports and structural type errors, but not field-level
typos like ``fields.Char(strng=...)``.

If field-arg validation becomes a goal later, replace the variadic
signatures with explicit overloads per field type.
"""

from datetime import date as _date, datetime as _datetime
from typing import Any


class Field:
    """Descriptor base for all Odoo fields.

    The ``__get__`` / ``__set__`` overloads model the descriptor protocol
    Odoo's real fields use: at class level, ``MyModel.foo`` is the Field
    declarator (typed as Field); at instance level, ``record.foo`` is the
    stored value (typed as Any so comparisons and string operations on
    field values type-check naturally — without this, ``self.my_char`` is
    a Field, not a str, and ``self.my_char == "x"`` triggers
    reportUnnecessaryComparison).
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __get__(self, instance: Any, owner: Any = None) -> Any: ...
    def __set__(self, instance: Any, value: Any) -> None: ...
    def __delete__(self, instance: Any) -> None: ...


class Char(Field): ...
class Text(Field): ...
class Html(Field): ...
class Integer(Field): ...
class Float(Field): ...
class Monetary(Field): ...
class Boolean(Field): ...


class Date(Field):
    """Adds Odoo's classmethod helpers ``today`` / ``context_today`` /
    ``to_date`` / ``to_string``. These are called as ``fields.Date.today()``
    on the class itself, not on a record."""

    @classmethod
    def today(cls, *args: Any) -> _date: ...
    @classmethod
    def context_today(cls, record: Any, timestamp: Any = None) -> _date: ...
    @classmethod
    def to_date(cls, value: Any) -> _date | None: ...
    @classmethod
    def to_string(cls, value: Any) -> str: ...
    @classmethod
    def from_string(cls, value: Any) -> _date | None: ...


class Datetime(Field):
    """Same classmethod surface as :class:`Date`, plus ``now``."""

    @classmethod
    def now(cls, *args: Any) -> _datetime: ...
    @classmethod
    def today(cls, *args: Any) -> _datetime: ...
    @classmethod
    def context_timestamp(cls, record: Any, timestamp: _datetime) -> _datetime: ...
    @classmethod
    def to_datetime(cls, value: Any) -> _datetime | None: ...
    @classmethod
    def to_string(cls, value: Any) -> str: ...
    @classmethod
    def from_string(cls, value: Any) -> _datetime | None: ...


class Selection(Field): ...
class Many2one(Field): ...
class One2many(Field): ...
class Many2many(Field): ...
class Binary(Field): ...
class Json(Field): ...
class Reference(Field): ...
