"""Stubs for ``odoo.fields``.

Each ``Field`` subclass accepts ``*args, **kwargs`` because Odoo's real
field constructors take dozens of keyword arguments (string, default,
help, required, readonly, related, compute, store, index, translate,
groups, copy, tracking, …) that are stable across versions but tedious
to enumerate. The trade-off is documented at module level — pyright
catches missing imports and structural type errors, but not field-level
typos like ``fields.Char(strng=...)``.

If field-arg validation becomes a goal later, replace the variadic
signatures with explicit overloads per field type.
"""

from typing import Any


class Field:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class Char(Field): ...
class Text(Field): ...
class Html(Field): ...
class Integer(Field): ...
class Float(Field): ...
class Monetary(Field): ...
class Boolean(Field): ...
class Date(Field): ...
class Datetime(Field): ...
class Selection(Field): ...
class Many2one(Field): ...
class One2many(Field): ...
class Many2many(Field): ...
class Binary(Field): ...
class Json(Field): ...
class Reference(Field): ...
